- name: add apt key for nodesource
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: install nodejs
  apt:
    name: ["nodejs", "npm"]
    state: latest

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present