- name: Create Backend Directory
  file:
    path: /home/ubuntu/backend
    state: directory
- pwd:
  shell: |
    pwd
    ll
- copy:
    src: ~/project/.circleci/ansible/roles/deploy/artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Start the app
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start