---
- name: Unarchive backend files
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: Install dependencies
  shell: |
    npm i

- name: "Start pm2 server"
  shell: |
    cd /dist
    pm2 stop default
    pm2 start npm --start
